version: '3.9'

services:
  backend:
    build: .
    container_name: django_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - ../static:/app/static                    
      - ../media:/app/media                     
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:15
    container_name: postgres_db
    volumes:
      - ../postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always

  frontend:
    build:
      context: ../maishagala-fe
    container_name: maishagala_fe
    ports:
      - "3000:81" # <-- Expose port 80 internally for reverse proxy
    restart: always
