"""
Django settings for test_devops project.
Generated by 'django-admin startproject' using Django 5.2.
"""

import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

# ===================== BASE CONFIG =====================

BASE_DIR = Path(__file__).resolve().parent.parent
ENV_MODE = os.getenv("ENV_MODE", "development")
SECRET_KEY = os.getenv("SECRET_KEY", "django-insecure-vsx!^0&h#i9=9^j#j*o^q^#b9_iy1yuxyddgr_-)&!#g6!u%@%")
DEBUG = ENV_MODE != "production"
ALLOWED_HOSTS = ['maishagala.com', 'www.maishagala.com', 'localhost', '127.0.0.1']

# ===================== APPLICATIONS =====================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'authentication',
    'dashboard',
    'community_hub',
]

# ===================== MIDDLEWARE =====================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'community_hub.middleware.restrict_panel.StaffAccessMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ===================== URLS & WSGI =====================

ROOT_URLCONF = 'test_devops.urls'

WSGI_APPLICATION = 'test_devops.wsgi.application'

# ===================== TEMPLATES =====================

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# ===================== DATABASE =====================

if ENV_MODE == "production":
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('POSTGRES_DB'),
            'USER': os.getenv('POSTGRES_USER'),
            'PASSWORD': os.getenv('POSTGRES_PASSWORD'),
            'HOST': os.getenv('POSTGRES_HOST'),
            'PORT': os.getenv('POSTGRES_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / "db.sqlite3",
        }
    }

# ===================== EMAIL =====================

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL')

# ===================== PASSWORD VALIDATION =====================

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ===================== CSRF ORIGIN =====================

CSRF_TRUSTED_ORIGINS = [
    "https://maishagala.com",
    "https://www.maishagala.com",
]

# ===================== I18N =====================

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# ===================== STATIC / MEDIA =====================

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static_src']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ===================== DEFAULT PRIMARY KEY =====================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
