# Generated by Django 4.2.20 on 2025-04-25 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community_hub', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-start_date']},
        ),
        migrations.RemoveField(
            model_name='event',
            name='ticket_price',
        ),
        migrations.RemoveField(
            model_name='tickettype',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='tickettype',
            name='quantity_available',
        ),
        migrations.RemoveField(
            model_name='tickettype',
            name='sale_end',
        ),
        migrations.RemoveField(
            model_name='tickettype',
            name='sale_start',
        ),
        migrations.AddField(
            model_name='eventimage',
            name='caption',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='max_guests',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('conference', 'Conference'), ('workshop', 'Workshop'), ('networking', 'Networking'), ('seminar', 'Seminar'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='community_hub.event'),
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='image',
            field=models.ImageField(upload_to='events/'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='description',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='MembershipTicketBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_type', models.CharField(choices=[('member', 'Member'), ('individual', 'Individual Member'), ('sponsor', 'Sponsor'), ('main_sponsor', 'Main Sponsor')], max_length=50)),
                ('free_ticket_count', models.PositiveIntegerField(default=1)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_benefits', to='community_hub.event')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_benefits', to='community_hub.tickettype')),
            ],
            options={
                'unique_together': {('event', 'membership_type', 'ticket_type')},
            },
        ),
    ]
